[package]
name = "auto-frs-schedule"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.20.0"
mysql_async = "0.32.2"
tokio = { version = "1", features = ["full"] }
cuid = "1.3.1"
clap = { version = "4.3.9", features = ["derive"] }
anyhow = "1.0.71"
