[package]
name = "auto-frs-schedule"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.20.0"
mysql_async = "0.32.2"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
cuid = "1.3.1"
clap = { version = "4.3.9", features = ["derive"] }
